KarateMVC/Controllers/SquadraDettsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KarateMVC.Models;

namespace KarateMVC.Controllers
{
    public class SquadraDettsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: SquadraDetts
        public ActionResult Index()
        {
            var squadraDetts = db.SquadraDetts.Include(s => s.Nome).Include(s => s.NomeSquadra);
            return View(squadraDetts.ToList());
        }

        public ActionResult Index1(int? id)
        {
            var squadre = db.SquadraDetts.Include(s => s.Nome).Include(s => s.NomeSquadra).Where(s=>s.Squadra_id == id);
            ViewBag.Squadre=squadre;
            return View();
        }

        // GET: SquadraDetts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SquadraDett squadraDett = db.SquadraDetts.Find(id);
            if (squadraDett == null)
            {
                return HttpNotFound();
            }
            return View(squadraDett);
        }

        // GET: SquadraDetts/Create
        public ActionResult Create()
        {
            ViewBag.Id = new SelectList(db.Users, "Id", "Nome");
            int sqid = Convert.ToInt32(Request.QueryString["squadra"]);
            var squadra = db.Squadres.Where(s => s.Squadra_id == sqid);
            ViewBag.Squadra = squadra;
            var allievi = db.Users.OrderBy(n => n.Nome).ToList();
            ViewBag.AllieviCount = allievi.Count();
            ViewBag.Allievi = allievi;
            return View();
        }

        // POST: SquadraDetts/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SquadraDett_id,Squadra_id,Id")] SquadraDett squadraDett)
        {
            ViewBag.Id = new SelectList(db.Users, "Id", "Nome");
            int sqid = Convert.ToInt32(Request.QueryString["squadra"]);
            var squadra = db.Squadres.Where(s => s.Squadra_id == sqid);
            ViewBag.Squadra = squadra;
            var allievi = db.Users.OrderBy(n => n.Nome).Select(u => new SelectListItem { Value = u.Id, Text = u.Nome });
            ViewBag.Allievi = allievi;
            var squadre = db.Squadres.OrderBy(a => a.Anno).Select(s => new SelectListItem { Value = s.Squadra_id.ToString(), Text = s.Anno + " - " + s.NomeSquadra });
            ViewBag.Squadra_id = new SelectList(squadre, "Value", "Text");
            if (ModelState.IsValid)
            {
                foreach (var item in allievi)
                {
                squadraDett.Squadra_id = sqid;
                db.SquadraDetts.Add(squadraDett);
                db.SaveChanges();

                }
                return RedirectToAction("Edit", "Squadres", new {id = sqid });
            }
            return View(squadraDett);
        }

        // GET: SquadraDetts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SquadraDett squadraDett = db.SquadraDetts.Find(id);
            if (squadraDett == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id = new SelectList(db.Users, "Id", "Nome", squadraDett.Id);
            ViewBag.Squadra_id = new SelectList(db.Squadres, "Squadra_id", "NomeSquadra", squadraDett.Squadra_id);
            return View(squadraDett);
        }

        // POST: SquadraDetts/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SquadraDett_id,Squadra_id,Id")] SquadraDett squadraDett)
        {
            if (ModelState.IsValid)
            {
                db.Entry(squadraDett).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id = new SelectList(db.Users, "Id", "Nome", squadraDett.Id);
            ViewBag.Squadra_id = new SelectList(db.Squadres, "Squadra_id", "NomeSquadra", squadraDett.Squadra_id);
            return View(squadraDett);
        }

        public ActionResult EditS(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var squadre = db.SquadraDetts.Where(s => s.Squadra_id == id).ToList();
            ViewBag.Squadre = squadre;
            return View();
        }
        // GET: SquadraDetts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SquadraDett squadraDett = db.SquadraDetts.Find(id);
            if (squadraDett == null)
            {
                return HttpNotFound();
            }
            return View(squadraDett);
        }

        // POST: SquadraDetts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            int sqid = Convert.ToInt32(Request.QueryString["squadra"]);
            SquadraDett squadraDett = db.SquadraDetts.Find(id);
            db.SquadraDetts.Remove(squadraDett);
            db.SaveChanges();
            return RedirectToAction("Edit", "Squadres", new { id = sqid });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KarateMVC/Views/SquadraDetts/Create.cshtml
@model KarateMVC.Models.SquadraDett

@{
    ViewBag.Title = "Aggiungi componenti alla squadra";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            <div class="control-label col-md-2"></div>
            <div class="col-md-10">
                @foreach (var item in ViewBag.Squadra)
                {
                    <h2>@item.Anno - @item.NomeSquadra</h2>

                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id, "Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model=>model.Id, new MultiSelectList(ViewBag.Allievi, "Id", "Nome"), new {@class="form-control", size = ViewBag.AllieviCount})
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aggiungi" class="btn btn-success" />
                <a href="@Url.Action("Edit", "Squadres", new {id = Request.QueryString["squadra"] })" class="btn btn-danger">Annulla</a>
            </div>
        </div>
    </div>
}

KarateMVC/Views/SquadraDetts/Delete.cshtml
@model KarateMVC.Models.SquadraDett

@{
    ViewBag.Title = "Delete";
}

<h2>Elimina componenti squadra</h2>

<h3>Se sicuro di cancellare questo allievo dalla squadra?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomeSquadra.NomeSquadra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeSquadra.NomeSquadra)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            <a href="@Url.Action("Edit", "Squadres", new { id = Request.QueryString["squadra"] })" class="btn btn-primary">Annulla</a> 
        </div>
    }
</div>

KarateMVC/Views/SquadraDetts/Details.cshtml
@model KarateMVC.Models.SquadraDett

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SquadraDett</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomeSquadra.NomeSquadra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeSquadra.NomeSquadra)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SquadraDett_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KarateMVC/Views/SquadraDetts/Edit.cshtml
@model KarateMVC.Models.SquadraDett

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SquadraDett</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SquadraDett_id)

        <div class="form-group">
            @Html.LabelFor(model => model.Squadra_id, "Squadra_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Squadra_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Squadra_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id, "Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KarateMVC/Views/SquadraDetts/EditS.cshtml
@model IEnumerable<KarateMVC.Models.SquadraDett>

@{
    ViewBag.Title = "EditS";
}

<h2>EditS</h2>

@foreach (var item in ViewBag.Squadre)
{
<img class="img-usr" src = "@Url.Content("~/Content/Immagini/FotoIscritti/" + @item.Id + ".jpg")" />
@Html.ActionLink("Cancella", "Delete", "SquadraDetts", new {id = item.SquadraDett_id })
}

KarateMVC/Views/SquadraDetts/Index.cshtml
@model IEnumerable<KarateMVC.Models.SquadraDett>

@{
    ViewBag.Title = "Dettaglio squadre";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeSquadra.NomeSquadra)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome.Nome)
        </td>
        <td>
            @item.NomeSquadra.Anno @Html.DisplayFor(modelItem => item.NomeSquadra.NomeSquadra)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SquadraDett_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.SquadraDett_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.SquadraDett_id })
        </td>
    </tr>
}

</table>

KarateMVC/Views/SquadraDetts/Index1.cshtml
@{
    ViewBag.Title = "Index1";
}

<h2>Index1</h2>