KarateMVC/Controllers/MedaglieresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KarateMVC.Models;
using Microsoft.AspNet.Identity;
using System.IO;

namespace KarateMVC.Controllers
{
    public class MedaglieresController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Medaglieres
        [Authorize]
        public ActionResult Index()
        {
            var utente = User.Identity.GetUserId();
            var medaglieres = db.Medaglieres.Include(m => m.Titolo).Where(m=>m.Uid == utente).OrderByDescending(m => m.Titolo.Data);
            ViewBag.MedCount = medaglieres.Count();
            ViewBag.Oro = medaglieres.Where(c => c.classifica == "1").Count();
            ViewBag.Argento = medaglieres.Where(c => c.classifica == "2").Count();
            ViewBag.Bronzo = medaglieres.Where(c => c.classifica == "3").Count();
            return View(medaglieres.ToList());
        }

        // GET: Medaglieres/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medagliere medagliere = db.Medaglieres.Find(id);
            if (medagliere == null)
            {
                return HttpNotFound();
            }
            return View(medagliere);
        }

        // GET: Medaglieres/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Evento_Id = new SelectList(db.Eventis.Where(g => g.NomeGara.Gara_Id != 19 && g.NomeGara.Gara_Id > 2).OrderByDescending(d => d.Data), "Evento_Id", "Titolo");
            return View();
        }

        // POST: Medaglieres/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Medagliere_Id,Evento_Id,Spec,classifica,Uid")] Medagliere medagliere)
        {
            if (ModelState.IsValid)
            {
                medagliere.Uid = User.Identity.GetUserId();
                db.Medaglieres.Add(medagliere);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Evento_Id = new SelectList(db.Eventis, "Evento_Id", "Titolo", medagliere.Evento_Id);
            return View(medagliere);
        }

        [Authorize]
        public ActionResult CreateUt(string id)
        {

            ViewBag.Bbb = "uuu!";
            ViewBag.Evento_Id = new SelectList(db.Eventis.Where(g => g.NomeGara.Gara_Id != 19 && g.NomeGara.Gara_Id > 2).OrderByDescending(d => d.Data), "Evento_Id", "Titolo");
            var utente = User.Identity.GetUserId();
            ViewBag.Utente = id;
            var medaglieres = db.Medaglieres.Include(m => m.Titolo).Where(m => m.Uid == id).OrderByDescending(d => d.Titolo.Data);
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult CreateUt(string id, [Bind(Include ="Medagliere_Id,Evento_Id,Spec,Classifica,Uid")] Medagliere medagliere)
        {
            if (ModelState.IsValid)
            {
                medagliere.Uid = id;
                db.Medaglieres.Add(medagliere);
                db.SaveChanges();
                return RedirectToAction("Index", "UsersAdmin");
            }
            ViewBag.Evento_Id = new SelectList(db.Eventis.Where(g => g.NomeGara.Gara_Id != 19 && g.NomeGara.Gara_Id > 2).OrderByDescending(d => d.Data), "Evento_Id", "Titolo");
            return View(medagliere);
        }
        // GET: Medaglieres/Edit/5

        [Authorize]
        public ActionResult CreateSq(string id)
        {
            ViewBag.Evento_Id = new SelectList(db.Eventis.Where(g => g.NomeGara.Gara_Id != 19 && g.NomeGara.Gara_Id > 2).OrderByDescending(d => d.Data), "Evento_Id", "Titolo");
            var utente = User.Identity.GetUserId();
            ViewBag.Utente = id;
            var medaglieres = db.Medaglieres.Include(m => m.Titolo).Where(m => m.Uid == id).OrderByDescending(d => d.Titolo.Data);
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult CreateSq(string id, [Bind(Include = "Medagliere_Id,Evento_Id,Spec,Classifica,Uid")] Medagliere medagliere)
        {
            medagliere.Spec = Request.QueryString["spec"];
            if (ModelState.IsValid)
            {
                medagliere.Uid = id;
                db.Medaglieres.Add(medagliere);
                db.SaveChanges();
                return RedirectToAction("Index", "UsersAdmin");
            }
            ViewBag.Evento_Id = new SelectList(db.Eventis.Where(g => g.NomeGara.Gara_Id != 19 && g.NomeGara.Gara_Id > 2).OrderByDescending(d => d.Data), "Evento_Id", "Titolo");
            return View(medagliere);
        }



        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medagliere medagliere = db.Medaglieres.Find(id);
            if (medagliere == null)
            {
                return HttpNotFound();
            }
            ViewBag.Evento_Id = new SelectList(db.Eventis.Where(g=>g.NomeGara.Gara_Id != 19 && g.NomeGara.Gara_Id > 2).OrderByDescending(d=>d.Data), "Evento_Id", "Titolo", medagliere.Evento_Id);
            return View(medagliere);
        }

        // POST: Medaglieres/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Medagliere_Id,Evento_Id,Spec,classifica,Uid")] Medagliere medagliere)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medagliere).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Evento_Id = new SelectList(db.Eventis, "Evento_Id", "Titolo", medagliere.Evento_Id);
            return View(medagliere);
        }

        // GET: Medaglieres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medagliere medagliere = db.Medaglieres.Find(id);
            if (medagliere == null)
            {
                return HttpNotFound();
            }
            return View(medagliere);
        }

        // POST: Medaglieres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Medagliere medagliere = db.Medaglieres.Find(id);
            db.Medaglieres.Remove(medagliere);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Palmares(string id)
        {
            //galleria immagini personale
            if (Directory.Exists(Server.MapPath("~/Content/Immagini/FotoPersonali/" + id + "/")))
            {
                var immagini = Directory.GetFiles(Server.MapPath("/Content/Immagini/FotoPersonali/" + id + "/"));
                ViewBag.Immagini = immagini.ToList();

            }
            var uid = id;
            ViewBag.Uid = uid;
            var utente = db.Users.Where(u=>u.Id == id );
            ViewBag.Utente = utente;
            var medaglieres = db.Medaglieres.Include(m => m.Titolo).Where(m => m.Uid == id).OrderByDescending(d=>d.Titolo.Data);
            ViewBag.MedCount = medaglieres.Count();
            ViewBag.Oro = medaglieres.Where(c => c.classifica == "1").Count();
            ViewBag.Argento = medaglieres.Where(c => c.classifica == "2").Count();
            ViewBag.Bronzo = medaglieres.Where(c => c.classifica == "3").Count();
            return View(medaglieres.ToList());
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KarateMVC/Controllers/SquadresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KarateMVC.Models;

namespace KarateMVC.Controllers
{
    public class SquadresController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Squadres
        public ActionResult Index()
        {
            var squadre = db.Squadres.OrderByDescending(a=>a.Anno).ToList();
            var medaglie = db.Medaglieres.OrderByDescending(a => a.classifica).ToList();
            ViewBag.Medaglie = medaglie;
            return View(squadre);
        }

        // GET: Squadres
        public ActionResult IndexUt()
        {
            var dettaglio = db.SquadraDetts.OrderBy(n => n.Nome.Nome).ToList();
            var squadre = db.Squadres.OrderByDescending(a => a.Anno).ToList();
            var palmares = db.Medaglieres.ToList();
            ViewData["Palmares"] = palmares;
            ViewBag.Palmares = palmares;
            ViewBag.Dettaglio = dettaglio;
            return View(squadre);
        }

        // GET: Squadres/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Squadre squadre = db.Squadres.Find(id);
            var allievi = db.SquadraDetts.Where(a=>a.Squadra_id==id);
            ViewBag.Allievi = allievi;
            if (squadre == null)
            {
                return HttpNotFound();
            }
            return View(squadre);
        }

        [Authorize(Roles = "Admin")]
        // GET: Squadres/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Squadres/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Squadra_id,Anno,NomeSquadra")] Squadre squadre)
        {
            if (ModelState.IsValid)
            {
                db.Squadres.Add(squadre);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(squadre);
        }

        // GET: Squadres/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Squadre squadre = db.Squadres.Find(id);
            if (squadre == null)
            {
                return HttpNotFound();
            }
            return View(squadre);
        }

        // POST: Squadres/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Squadra_id,Anno,NomeSquadra")] Squadre squadre)
        {
            if (ModelState.IsValid)
            {
                db.Entry(squadre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(squadre);
        }

        // GET: Squadres/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Squadre squadre = db.Squadres.Find(id);
            if (squadre == null)
            {
                return HttpNotFound();
            }
            return View(squadre);
        }

        // POST: Squadres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Squadre squadre = db.Squadres.Find(id);
            db.Squadres.Remove(squadre);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KarateMVC/Views/Squadres/Create.cshtml
@model KarateMVC.Models.Squadre

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Squadre</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Anno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Anno, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Anno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NomeSquadra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeSquadra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeSquadra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KarateMVC/Views/Squadres/Delete.cshtml
@model KarateMVC.Models.Squadre

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Squadre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Anno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomeSquadra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeSquadra)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KarateMVC/Views/Squadres/Details.cshtml
@model KarateMVC.Models.Squadre

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Squadre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Anno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomeSquadra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeSquadra)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Squadra_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KarateMVC/Views/Squadres/Edit.cshtml
@model KarateMVC.Models.Squadre

@{
    ViewBag.Title = "Edit";
}

<h2>Modifica squadre</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Squadra_id)

        <div class="form-group">
            @Html.LabelFor(model => model.Anno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NomeSquadra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeSquadra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeSquadra, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-1 pull-left text-center">
                <a href="@Url.Action("Create", "SquadraDetts", new {squadra = Model.Squadra_id })"><span class="glyphicon glyphicon-plus h2 text-info"></span></a>
            </div>

                @foreach (var item in Model.Squadres)
                {
                    <div class="col-md-1 pull-left text-center">
                        <a href="@Url.Action("Delete", "SquadraDetts", new { id = item.SquadraDett_id, squadra = Model.Squadra_id })"><span class="glyphicon glyphicon-remove text-danger"></span></a><br />
                        <img class="img-usr" src="@Url.Content("/Content/Immagini/FotoIscritti/" + @item.Id  + ".jpg")" /><br />
                        <br />
                        @item.Nome.Nome


                    </div>
                }
            </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
            </div>
        </div>
    </div>

<div>
                <input type="submit" value="Fatto" class="btn btn-primary" />
</div>
}

KarateMVC/Views/Squadres/Index.cshtml
@model IEnumerable<KarateMVC.Models.Squadre>

@{
    ViewBag.Title = "Squadre";
}

<h2>@ViewBag.Title</h2>
@if (User.IsInRole("Admin"))
{
<p>
    <a href="@Url.Action("Create", "Squadres")" class="btn btn-primary"><span class="badge">@ViewBag.SquadreCount</span> Nuovo</a>
</p>
}
<table class="table table-striped">
    @foreach (var group in Model.GroupBy(item => item.Anno))
    {
        <tr>
            <td>
                <a role="button" data-toggle="collapse" href="#@Html.Encode(group.Key)" aria-expanded="false" aria-controls="collapseExample">
                    <span class="h2">@Html.Encode(group.Key)</span>
                </a>
                <div class="text-info collapse" id="@Html.Encode(group.Key)">
                    @foreach (var group1 in group.OrderBy(n => n.NomeSquadra).GroupBy(item1 => item1.NomeSquadra))
                    {
                        <ul class="well list-unstyled">
                            <li>
                                <span class="badge">@Html.Encode(group1.Key)</span>
                                @foreach (var group2 in group1)
                                {
                                    <div class="row">
                                        <span>@group2.Squadra_id</span>
                                        <a href="@Url.Action("Palmares", "Medaglieres", new { id= group2.Squadra_id})"><span class="glyphicon glyphicon-cd"></span></a>
                                        @if (User.IsInRole("Admin"))
                                        {
                                            <a href="@Url.Action("Edit", "Squadres", new{id = group2.Squadra_id })" class="pull-right">    <span class="glyphicon glyphicon-pencil"></span></a>
                                                <a href="@Url.Action("CreateSq", "Medaglieres", new{id = group2.Squadra_id, spec = group2.NomeSquadra })" title="Inserisci risultato" class="pull-right"><span class="glyphicon glyphicon-cd pull-right"></span></a>
                                        }
                                        @foreach (var group3 in group2.Squadres)
                                        {
                                            <div class="col-md-1 pull-left text-center">
                                                <a href="@Url.Action("Palmares", "Medaglieres", new { id = @group3.Nome.Id})">
                                                    @if (File.Exists(Server.MapPath("/Content/Immagini/FotoIscritti/" + @group3.Id + ".jpg")))
                                                    {
                                                        <img class="img-usr" src="@Url.Content("/Content/Immagini/FotoIscritti/" + @group3.Id  + ".jpg")" /><br />
                                                    }
                                                    else
                                                    {
                                                       <img class="img-usr" src="@Url.Content("/Content/Immagini/FotoIscritti/anonimous.jpg")" /><br />
                                                    }
                                                    @group3.Nome.Nome
                                                </a>
                                            </div>
                                        }
                                    </div>
                                }

                            </li>
                        </ul>
                    }

                </div>
            </td>
        </tr>
    }

</table>

KarateMVC/Views/Squadres/IndexUt.cshtml
@model IEnumerable<KarateMVC.Models.Squadre>

@{
    ViewBag.Title = "Squadre";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    @foreach (var group in Model.GroupBy(item => item.Anno))
    {
        <tr>
            <td>
                @*Modal trigger*@
                <a role="button" data-toggle="collapse" href="#@Html.Encode(group.Key)" aria-expanded="false" aria-controls="collapseExample">
                    <span class="h2">@Html.Encode(group.Key)</span>
                </a>
                @*Modal box*@
                <div class="text-info collapse" id="@Html.Encode(group.Key)">
                    @foreach (var group1 in group.OrderBy(n => n.NomeSquadra).GroupBy(item1 => item1.NomeSquadra))
                        {
                                <ul class="well">
                                    <li>
                                        <span class="h3">@Html.Encode(group1.Key)</span>
                                        @foreach (var group2 in group1)
                                        {
                                            <div class="row">
                                                <span>Squadra Id: @group2.Squadra_id</span>
                                                <span>Nome squadra: @group2.NomeSquadra</span>
                                                <span>Anno: @group2.Anno</span>
                                                <span>Boh @group2.Squadres</span> 
                                                @foreach (var group3 in group2.Squadres)
                                                {
                                                    <div class="col-md-1 text-center">
                                                        <a href="@Url.Action("Palmares", "Medaglieres", new {id = @group3.Id })">
                                                        @if (File.Exists(@Server.MapPath("/Content/Immagini/FotoIscritti/" + @group3.Id + ".jpg")))
                                                        {
                                                            <img class="img-usr" src="@Url.Content("/Content/Immagini/FotoIscritti/" + @group3.Id  + ".jpg")" />
                                                        }
                                                        else
                                                        {
                                                            <img class="img-usr" src="@Url.Content("/Content/Immagini/FotoIscritti/anonimous.jpg")" />

                                                        }
                                                            <br />@group3.Nome.Nome 
                                                        </a>
                                                    </div>
                                                }
                                            </div>
                                        }
                                    </li>
                                </ul>
                            }
                </div>

           </td>
        </tr>
    }

</table>