KarateMVC/Controllers/AvatarController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace KarateMVC.Controllers
{
    public class AvatarController : Controller
    {
        private const int AvatarStoredWidth = 100;  // ToDo - Change the size of the stored avatar image
        private const int AvatarStoredHeight = 100; // ToDo - Change the size of the stored avatar image
        private const int AvatarScreenWidth = 400;  // ToDo - Change the value of the width of the image on the screen

        private const string TempFolder = "/Temp";
        private const string MapTempFolder = "~" + TempFolder;
        private const string AvatarPath = "/Content/Immagini/FotoIscritti";

        private readonly string[] _imageFileExtensions = { ".jpg", ".png", ".gif", ".jpeg" };

        [HttpGet]
        public ActionResult Upload()
        {
            return View();
        }

        [HttpGet]
        public ActionResult _Upload()
        {
            return PartialView();
        }

        [ValidateAntiForgeryToken]
        public ActionResult _Upload(IEnumerable<HttpPostedFileBase> files)
        {
            if (files == null || !files.Any()) return Json(new { success = false, errorMessage = "No file uploaded." });
            var file = files.FirstOrDefault();  // get ONE only
            if (file == null || !IsImage(file)) return Json(new { success = false, errorMessage = "File is of wrong format." });
            if (file.ContentLength <= 0) return Json(new { success = false, errorMessage = "File cannot be zero length." });
            var webPath = GetTempSavedFilePath(file);
            //mistertommat - 18 Nov '15 - replacing '\' to '//' results in incorrect image url on firefox and IE,
            //                            therefore replacing '\\' to '/' so that a proper web url is returned.            
            return Json(new { success = true, fileName = webPath.Replace("\\", "/") }); // success
        }

        [HttpPost]
        public ActionResult Save(string t, string l, string h, string w, string fileName)
        {
            try
            {
                // Calculate dimensions
                var top = Convert.ToInt32(t.Replace("-", "").Replace("px", ""));
                var left = Convert.ToInt32(l.Replace("-", "").Replace("px", ""));
                var height = Convert.ToInt32(h.Replace("-", "").Replace("px", ""));
                var width = Convert.ToInt32(w.Replace("-", "").Replace("px", ""));
                var extension = Path.GetExtension(fileName);
                var uid = User.Identity.GetUserId();

                // Get file from temporary folder
                var fn = Path.Combine(Server.MapPath(MapTempFolder), Path.GetFileName(fileName));
                // ...get image and resize it, ...
                var img = new WebImage(fn);
                img.Resize(width, height);
                // ... crop the part the user selected, ...
                img.Crop(top, left, img.Height - top - AvatarStoredHeight, img.Width - left - AvatarStoredWidth);
                // ... delete the temporary file,...
                System.IO.File.Delete(fn);
                // ... and save the new one.
                var newFileName = Path.Combine(AvatarPath, uid + extension);
                var newFileLocation = HttpContext.Server.MapPath(newFileName);
                if (Directory.Exists(Path.GetDirectoryName(newFileLocation)) == false)
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(newFileLocation));
                }

                img.Save(newFileLocation);
                return Json(new { success = true, avatarFileLocation = newFileName });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errorMessage = "Unable to upload file.\nERRORINFO: " + ex.Message });
            }
        }

        private bool IsImage(HttpPostedFileBase file)
        {
            if (file == null) return false;
            return file.ContentType.Contains("image") ||
                _imageFileExtensions.Any(item => file.FileName.EndsWith(item, StringComparison.OrdinalIgnoreCase));
        }

        private string GetTempSavedFilePath(HttpPostedFileBase file)
        {
            // Define destination
            var serverPath = HttpContext.Server.MapPath(TempFolder);
            if (Directory.Exists(serverPath) == false)
            {
                Directory.CreateDirectory(serverPath);
            }

            // Generate unique file name
            var fileName = Path.GetFileName(file.FileName);
            fileName = SaveTemporaryAvatarFileImage(file, serverPath, fileName);

            // Clean up old files after every save
            CleanUpTempFolder(1);
            return Path.Combine(TempFolder, fileName);
        }

        private static string SaveTemporaryAvatarFileImage(HttpPostedFileBase file, string serverPath, string fileName)
        {
            var img = new WebImage(file.InputStream);
            var ratio = img.Height / (double)img.Width;
            img.Resize(AvatarScreenWidth, (int)(AvatarScreenWidth * ratio));

            var fullFileName = Path.Combine(serverPath, fileName);
            if (System.IO.File.Exists(fullFileName))
            {
                System.IO.File.Delete(fullFileName);
            }

            img.Save(fullFileName);
            return Path.GetFileName(img.FileName);
        }

        private void CleanUpTempFolder(int hoursOld)
        {
            try
            {
                var currentUtcNow = DateTime.UtcNow;
                var serverPath = HttpContext.Server.MapPath("/Temp");
                if (!Directory.Exists(serverPath)) return;
                var fileEntries = Directory.GetFiles(serverPath);
                foreach (var fileEntry in fileEntries)
                {
                    var fileCreationTime = System.IO.File.GetCreationTimeUtc(fileEntry);
                    var res = currentUtcNow - fileCreationTime;
                    if (res.TotalHours > hoursOld)
                    {
                        System.IO.File.Delete(fileEntry);
                    }
                }
            }
            catch
            {
                // Deliberately empty.
            }
        }
    }
}

KarateMVC/Controllers/SquadresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KarateMVC.Models;

namespace KarateMVC.Controllers
{
    public class SquadresController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Squadres
        public ActionResult Index()
        {
            var squadre = db.Squadres.OrderByDescending(a=>a.Anno).ToList();
            var medaglie = db.Medaglieres.OrderByDescending(a => a.classifica).ToList();
            ViewBag.Medaglie = medaglie;
            return View(squadre);
        }

        // GET: Squadres
        public ActionResult IndexUt()
        {
            var dettaglio = db.SquadraDetts.OrderBy(n => n.Nome.Nome).ToList();
            var squadre = db.Squadres.OrderByDescending(a => a.Anno).ToList();
            var palmares = db.Medaglieres.ToList();
            ViewData["Palmares"] = palmares;
            ViewBag.Palmares = palmares;
            ViewBag.Dettaglio = dettaglio;
            return View(squadre);
        }

        // GET: Squadres/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Squadre squadre = db.Squadres.Find(id);
            var allievi = db.SquadraDetts.Where(a=>a.Squadra_id==id);
            ViewBag.Allievi = allievi;
            if (squadre == null)
            {
                return HttpNotFound();
            }
            return View(squadre);
        }

        [Authorize(Roles = "Admin")]
        // GET: Squadres/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Squadres/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Squadra_id,Anno,NomeSquadra")] Squadre squadre)
        {
            if (ModelState.IsValid)
            {
                db.Squadres.Add(squadre);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(squadre);
        }

        // GET: Squadres/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Squadre squadre = db.Squadres.Find(id);
            if (squadre == null)
            {
                return HttpNotFound();
            }
            return View(squadre);
        }

        // POST: Squadres/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Squadra_id,Anno,NomeSquadra")] Squadre squadre)
        {
            if (ModelState.IsValid)
            {
                db.Entry(squadre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(squadre);
        }

        // GET: Squadres/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Squadre squadre = db.Squadres.Find(id);
            if (squadre == null)
            {
                return HttpNotFound();
            }
            return View(squadre);
        }

        // POST: Squadres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Squadre squadre = db.Squadres.Find(id);
            db.Squadres.Remove(squadre);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KarateMVC/Views/UsersAdmin/Create.cshtml
@model KarateMVC.Models.RegisterViewModel

@{
    ViewBag.Title = "Gestione utenti";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Nuovo</h4>
    <hr class="hr1" />
    @Html.ValidationSummary("", new { @class = "text-error" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">
            Select User Role
        </label>
        <div class="col-md-10">
            @foreach (var item in (SelectList)ViewBag.RoleId)
            {
                <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                @Html.Label(item.Value, new { @class = "control-label" })
            }
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KarateMVC/Views/UsersAdmin/Delete.cshtml
@model KarateMVC.Models.ApplicationUser
@{
    ViewBag.Title = "Gestione utenti";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Cancella</h4>
    <h3>Sei sicuro di voler cancellare questo utente?</h3>
    <hr class="hr1"/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KarateMVC/Views/UsersAdmin/Details.cshtml
@model KarateMVC.Models.ApplicationUser

@{
    ViewBag.Title = "Gestione utenti";
}

<h2>@ViewBag.Title</h2>
<div>
    <hr class="hr1" />
    <div class="row">
        <div class="col col-md-2">
            <img class="img-responsive" src="@Url.Content("~/Content/Immagini/FotoIscritti/" + Model.Id + ".jpg")" />

        </div>
        <div class="col col-md-3">
            <h3>@Model.Nome @Model.Cognome</h3>
            @Html.DisplayFor(model => model.UserName)<br/>
            @String.Format("{0:dddd dd-MM-yyyy}", Model.DataNascita)
            @Model.Frase<br />
        </div>
    </div>
</div>
<hr class="hr1" />
<h4>Ruoli di appartenenza</h4>
@Html.Display(User.Identity.Name.ToString())
@if (ViewBag.RoleNames.Count == 0)
{
    <hr />
    <p>Nessun ruolo assegnato a questo utente</p>
}

<table class="table">

    @foreach (var item in ViewBag.RoleNames)
    {
        <tr>
            <td>
                @item
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Modifica", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Torna alla lista", "Index")
</p>

KarateMVC/Views/UsersAdmin/Edit.cshtml
@model KarateMVC.Models.EditUserViewModel

@{
    ViewBag.Title = "Gestione utenti";
}

<h2>@ViewBag.Title</h2>

        <h4>Modifica</h4>
        <hr class="hr1" />
        <div class="row">
            <div class="col col-md-4 text-center">
                <img class="img-thumbnail" src='@Url.Content("~/Content/Immagini/FotoIscritti/" + ViewBag.Uid + ".jpg")' />
            </div>
            <div class="col col-md-8">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Email)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Nome, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Nome)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Cognome, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Cognome, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Cognome)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.DataNascita, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @*Incompatibilità jquery validation date per Chrome e FireFox*@
                            @{ if (Request.Browser.Browser != "IE")
                                {
                                    Html.EnableClientValidation(false);
                                }

                            }
                            @Html.TextBoxFor(model => model.DataNascita, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker" })
                            @Html.ValidationMessageFor(model => model.DataNascita)
                            @{ Html.EnableClientValidation(true);}
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.AnnoInizio, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.AnnoInizio, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.AnnoInizio)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Grado, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Grado, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Grado)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Kata, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Kata, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Kata)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Frase, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(m => m.Frase, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Frase)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2">Livello</label>
                        <div class="col-md-10">
                            @Html.LabelFor(model => model.Maestro, new { @class = "control-label" })
                            @Html.CheckBoxFor(m => m.Maestro, new { @class = "checkbox-inline" })
                            @Html.ValidationMessageFor(model => model.Maestro)
                            @Html.LabelFor(model => model.Istruttore, new { @class = "control-label" })
                            @Html.CheckBoxFor(m => m.Istruttore, new { @class = "checkbox-inline" })
                            @Html.ValidationMessageFor(model => model.Istruttore)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-10">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            @Html.Label("Roles", new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @foreach (var item in Model.RolesList)
                {
                                    <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                                    @Html.Label(item.Value, new { @class = "control-label" })<br />

                                }
                            </div>


                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
                }

            </div>
        </div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $('.datepicker').datepicker("option", "dateFormat", "dd/mm/yyyy");
    </script>

}

KarateMVC/Views/UsersAdmin/EditImgUt.cshtml
@model KarateMVC.Models.ApplicationUser

@{
    ViewBag.Title = "Foto profilo utente";
}

<h2>@ViewBag.Title</h2>

<div>
    <h3>@Model.Nome</h3>
    <hr class="hr1" />
    <div class="row">
        <div class="col col-md-3">
            <img class="img-thumbnail" src="@Url.Content("~/Content/Immagini/FotoIscritti/" + Model.Id + ".jpg")" />
        </div>
        <div class="col col-md-9">
            @using (Html.BeginForm("EditImgUt", "UsersAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <input type="file" name="file" /><br>
                <input type="submit" value="Upload Image" class="btn btn-primary" />
                <br>
                <span class="label label-danger">@ViewBag.Message</span>

            }
        </div>
    </div>
</div>

KarateMVC/Views/UsersAdmin/EditUs.cshtml
@model KarateMVC.Models.EditUsViewModel
@{
    ViewBag.Title = "Gestione profilo";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Modifica dati anagrafici</h4>
        <hr class="hr1" />
        <h3>
            @Html.ActionLink(" ", "IndexUs", "UsersAdmin", null, new { @class = "glyphicon glyphicon-arrow-left" })
        </h3>

        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Nome)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Cognome, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Cognome, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cognome)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DataNascita, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*Incompatibilità jquery validation date per Chrome e FireFox*@
                @{ if (Request.Browser.Browser != "IE")
                    {
                        Html.EnableClientValidation(false);
                    }

                }
                @Html.TextBoxFor(model => model.DataNascita, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker" })
                @Html.ValidationMessageFor(model => model.DataNascita)
                @{ Html.EnableClientValidation(true);}
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AnnoInizio, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.AnnoInizio, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AnnoInizio)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Grado, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Grado, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Grado)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Kata, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Kata, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Kata)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Frase, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.Frase, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Frase)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<h3>
    @Html.ActionLink(" ", "IndexUs", "UsersAdmin", null, new { @class = "glyphicon glyphicon-arrow-left" })
</h3>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
            $('.datepicker').datepicker("option", "dateFormat", "dd/mm/yyyy");
    </script>
}

KarateMVC/Views/UsersAdmin/FotoProfilo.cshtml
@{
    ViewBag.Title = "Gestione profilo";
}

<h2>@ViewBag.Title</h2>
<h4>Modifica la foto del tuo profilo</h4>

@using (Html.BeginForm("FotoProfilo", "UsersAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<input id="file" name="file" type="file" /><br />
    <label class="alert-warning"> Solo file immagini JPG. Dimensione ottimale in pixel 200x200</label><br/>
    <span class="alert-danger">@ViewBag.Message</span><br />
<img class="img-responsive" src ="@Url.Content("~/Content/Immagini/FotoIscritti/" + @ViewBag.uid + ".jpg")" /><br/>
<input id="Button1" class="btn btn-primary" type="submit" value="Carica" />
@Html.ActionLink("Torna a gestione profilo", "IndexUs", null, new { @class = "btn btn-danger" })
}

KarateMVC/Views/UsersAdmin/Index.cshtml
@model IEnumerable<KarateMVC.Models.ApplicationUser>

@{
    ViewBag.Title = "Gestione utenti";
}

<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="col col-md-8">
        <a href="~@Url.Action("Create", "UserAdmin")" class="btn btn-primary"><span class="badge">@ViewBag.UtentiCount</span> Nuovo</a>
    </div>
    <div class="col col-md-4 text-right">
        @Html.ActionLink(" ", "Index", "Squadres", null, new { @class = "glyphicon glyphicon-knight", title = "Gestione squadre" })
    </div>
</div>
<p>
</p>
<table class="table table-hover tablef">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)


            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cognome)
            </th>
            <th></th>
        </tr>

    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (File.Exists(@Server.MapPath("/Content/Immagini/FotoIscritti/" + @Html.DisplayFor(modelItem => item.Id) + ".jpg")))
                {
                    <img class="img-usr" src="@Url.Content("~/Content/Immagini/FotoIscritti/" + @Html.DisplayFor(modelItem => item.Id) + ".jpg")" />
                }
                else
                {
                    <img class="img-usr" src="@Url.Content("~/Content/Immagini/FotoIscritti/Anonimous.jpg")" />
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)


            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cognome)


            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                @Html.ActionLink(" ", "CreateUt", "Medaglieres", new { id = item.Id }, new { @class = "glyphicon glyphicon-cd", title = "Inserisci risultato" }) |
                @Html.ActionLink(" ", "Album", "Home", new { id = item.Id }, new { @class = "glyphicon glyphicon-picture", title = "Album personale" }) |
                @Html.ActionLink(" ", "EditImgUt", "UsersAdmin", new { id = item.Id }, new { @class = "fa fa-user-circle", title = "Foto profilo" })
           </td>
        </tr>
    }

</table>

KarateMVC/Views/UsersAdmin/IndexUs.cshtml
@{
    ViewBag.Title = "Gestione profilo";
}

<h2>@ViewBag.Title</h2>
<h4>Modifica i dati del profilo</h4>
<ul class="list-unstyled">
    <li>
        <h3><span class="glyphicon glyphicon-floppy-saved"> @Html.ActionLink("Cambia password", "ChangePassword", "Manage")</span></h3>
    </li>
    <li>
        <h3><span class="glyphicon glyphicon-duplicate"> @Html.ActionLink("Dati anagrafici", "EditUs", new { id = @ViewBag.Uid })</span></h3>
    </li>
    <li>
        <h3><span class="glyphicon glyphicon-camera"> @Html.ActionLink("Foto profilo", "Upload", "Avatar", new { id = @ViewBag.Uid }, null)</span></h3>
    </li>
    <li>
        <h3><span class="glyphicon glyphicon-cd"> @Html.ActionLink("Medagliere", "Index", "Medaglieres", new { id = @ViewBag.Uid }, null)</span></h3>
    </li>
    <li>
        <h3><span class="glyphicon glyphicon-film"> @Html.ActionLink("Album fotografico", "Album", "Home", new { id = @ViewBag.Uid }, null)</span></h3>
    </li>
</ul>