KarateMVC/Controllers/DocumentisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KarateMVC.Models;
using System.IO;

namespace KarateMVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DocumentisController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Documentis
        public ActionResult Index()
        {
            ViewBag.PdfCount = db.Documentis.Count();
            var documenti = db.Documentis.OrderByDescending(i => i.Id);
            return View(documenti);
        }

        // GET: Documentis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Documenti documenti = db.Documentis.Find(id);
            if (documenti == null)
            {
                return HttpNotFound();
            }
            return View(documenti);
        }

        // GET: Documentis/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Documentis/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase file, [Bind(Include = "Id,Titolo,descrizione")] Documenti documenti)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0 && Path.GetExtension(file.FileName)== ".pdf")
                    try
                    {
                        db.Documentis.Add(documenti);
                        db.SaveChanges();
                        string estensione = Path.GetExtension(file.FileName);
                        string path = Path.Combine(Server.MapPath("/Content/Download"),
                                                   Path.GetFileName(documenti.Id.ToString() + estensione));
                        file.SaveAs(path);
                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                else
                {
                    ViewBag.Message = "Non hai selezionato nessun file. Puoi inserire solo file PDF";
                }
            }

            return View(documenti);
        }

        // GET: Documentis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Documenti documenti = db.Documentis.Find(id);
            if (documenti == null)
            {
                return HttpNotFound();
            }
            return View(documenti);
        }

        // POST: Documentis/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Titolo,descrizione")] Documenti documenti)
        {
            if (ModelState.IsValid)
            {
                db.Entry(documenti).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(documenti);
        }

        // GET: Documentis/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Documenti documenti = db.Documentis.Find(id);
            if (documenti == null)
            {
                return HttpNotFound();
            }
            return View(documenti);
        }

        // POST: Documentis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Documenti documenti = db.Documentis.Find(id);
            db.Documentis.Remove(documenti);
            db.SaveChanges();
            string filepath = Request.MapPath("~/Content/Download/" + id + ".pdf");
            if (System.IO.File.Exists(filepath))
            {
                System.IO.File.Delete(filepath);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KarateMVC/Controllers/EventisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KarateMVC.Models;
using System.Web.Helpers;
using System.IO;

namespace KarateMVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EventisController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Eventis
        public ActionResult Index()
        {
            ViewBag.EventiCount = db.Eventis.Count();
            var eventi = db.Eventis.OrderByDescending(d => d.Data);
            return View(eventi);
        }

        // GET: Eventis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Eventi eventi = db.Eventis.Find(id);
            if (eventi == null)
            {
                return HttpNotFound();
            }
            return View(eventi);
        }

        // GET: Eventis/Create
        public ActionResult Create()
        {
            ViewBag.Gara_Id = new SelectList(db.Gares.OrderBy(t => t.NomeGara), "Gara_Id", "NomeGara");
            return View();
        }
        
        // POST: Eventis/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Evento_Id,Gara_Id,Titolo,Data,DataP,DataF,Pubblica,Approfondimento,Galleria", Exclude ="Descrizione")] Eventi eventi)
        {
            FormCollection collection = new FormCollection(Request.Unvalidated().Form);
            eventi.Descrizione = collection["Descrizione"];
            if (ModelState.IsValid)
            {
                db.Eventis.Add(eventi);
                db.SaveChanges();
                    Directory.CreateDirectory(Server.MapPath("~/Content/Immagini/Eventi/" + eventi.Evento_Id));
                return RedirectToAction("Index");
            }
            ViewBag.Gara_Id = new SelectList(db.Gares, "Gara_Id", "NomeGara", eventi.Gara_Id);
            return View();
        }

        // GET: Eventis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Eventi eventi = db.Eventis.Find(id);
            if (eventi == null)
            {
                return HttpNotFound();
            }
            ViewBag.Gara_Id = new SelectList(db.Gares.OrderBy(t=>t.NomeGara), "Gara_Id", "NomeGara", eventi.Gara_Id);
            return View(eventi);
        }

        // POST: Eventis/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Evento_Id,Gara_Id,Titolo,Data,DataP,DataF,Pubblica,Approfondimento,Galleria", Exclude ="Descrizione")] Eventi eventi)
        {
            FormCollection collection = new FormCollection(Request.Unvalidated().Form);
            eventi.Descrizione = collection["Descrizione"];

            if (ModelState.IsValid)
            {
                db.Entry(eventi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Gara_Id = new SelectList(db.Gares, "Gara_Id", "NomeGara", eventi.Gara_Id);
            return View(eventi);
        }

        //Gestione immagine evento
        public ActionResult EditImgP(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var immagini = Directory.GetFiles(Server.MapPath("/Content/Immagini/Eventi/" + id + "/"));
            ViewBag.Immagini = immagini.ToList();
            Eventi eventi = db.Eventis.Find(id);
            if (eventi == null)
            {
                return HttpNotFound();
            }
            return View(eventi);
        }

        [HttpPost]
        public ActionResult EditImgP(HttpPostedFileBase file, int? id)
        {
            if (file != null)
                try
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Immagini/Eventi/" + id + "/"), id + ".jpg");
                    WebImage img = new WebImage(file.InputStream);
                    var larghezza = img.Width;
                    var altezza = img.Height;
                    var rapportoO = larghezza / altezza;
                    var rapportoV = altezza / larghezza;
                    if (altezza > 1900 | larghezza > 1900)
                    {
                        if (rapportoO >= 1)
                        {
                            ViewBag.Message = "Attendi la fine del download...";
                            img.Resize(1900, 1900 / rapportoO);
                            img.Save(path);
                            ViewBag.Message = "Download immagine orizzontale avvenuto con successo. Dimensione immagine originale: larghezza " + larghezza + " Altezza " + altezza;
                        }
                        else
                        {
                            img.Resize(800 / rapportoV, 800);
                            img.Save(path);
                            ViewBag.Message = "Download immagine verticale avvenuto con successo. Dimensione immagine: larghezza " + larghezza + "Altezza" + altezza;
                        }
                    }
                    else
                    {
                        if (rapportoO >= 1)
                        {
                            ViewBag.Message = "Attendi la fine del download...";
                            img.Save(path);
                            ViewBag.Message = "Download immagine orizzontale avvenuto con successo. Dimensione immagine originale: larghezza " + larghezza + " Altezza " + altezza;
                        }
                        else
                        {
                            ViewBag.Message = "Attendi la fine del download...";
                            img.Save(path);
                            ViewBag.Message = "Download immagine verticale avvenuto con successo. Dimensione immagine: larghezza " + larghezza + "Altezza" + altezza;
                        }
                    }


                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            else
            {
                ViewBag.Message = "Devi scegliere un file";
            }
            var immagini = Directory.GetFiles(Server.MapPath("/Content/Immagini/Eventi/" + id + "/"));
            ViewBag.Immagini = immagini.ToList();
            Eventi eventi = db.Eventis.Find(id);
            if (eventi == null)
            {
                return HttpNotFound();
            }
            return View(eventi);

        }

        //Gestione immagini galleria fotografica
        public ActionResult EditImg(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var immagini = Directory.GetFiles(Server.MapPath("/Content/Immagini/Eventi/" + id + "/"));
            ViewBag.Immagini = immagini.ToList();
            Eventi eventi = db.Eventis.Find(id);
            if (eventi == null)
            {
                return HttpNotFound();
            }
            return View(eventi);
        }

        [HttpPost]
        public ActionResult EditImg(IEnumerable<HttpPostedFileBase> files, int? id)
        {
            foreach (var file in files)
            {
                if (file != null)
                    try
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/Immagini/Eventi/" + id + "/"), fileName);
                        WebImage img = new WebImage(file.InputStream);
                        var larghezza = img.Width;
                        var altezza = img.Height;
                        var rapportoO = larghezza / altezza;
                        var rapportoV = altezza / larghezza;
                        if (altezza > 1900 | larghezza > 1900)
                        {
                            if (rapportoO >= 1)
                            {
                                ViewBag.Message = "Attendi la fine del download...";
                                img.Resize(1900, 1900 / rapportoO);
                                img.Save(path);
                                ViewBag.Message = "Download immagine orizzontale avvenuto con successo. Dimensione immagine originale: larghezza " + larghezza + " Altezza " + altezza;
                            }
                            else
                            {
                                ViewBag.Message = "Attendi la fine del download...";
                                img.Resize(800 / rapportoV, 800);
                                img.Save(path);
                                ViewBag.Message = "Download immagine verticale avvenuto con successo. Dimensione immagine: larghezza " + larghezza + "Altezza" + altezza;
                            }
                        }
                        else
                        {
                            if (rapportoO >= 1)
                            {
                                ViewBag.Message = "Attendi la fine del download...";

KarateMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/lightbox.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr.custom.js"></script>
    <title>@ViewBag.Title - Shotokenshukai</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <header>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <a class="link-home" href='@Url.Action("Index", "Home")'><img src="~/Content/Immagini/ScrittaTrasparenteG.png" /><span class="scrittaLogo">Shotokenshukai Caravaggio</span></a>
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navi">
                        <li><div><a href="@Url.Action("Appuntamenti", "Home")" class="glyphicon glyphicon-calendar"><span>Appuntamenti</span></a></div></li>
                        <li><div><a href="@Url.Action("Corsi", "Home")" class="glyphicon glyphicon-education"><span>Orari</span></a></div></li>
                        <li><div><a href="@Url.Action("Palestra", "Home")" class="glyphicon glyphicon-tower"><span>Palestra</span></a></div></li>
                        <li><div><a href="@Url.Action("Eventi", "Home")" class="glyphicon glyphicon-film"><span>Eventi</span></a></div></li>
                        @if (Request.IsAuthenticated)
                        {
                            <li><div><a href="@Url.Action("Download", "Home")" class="glyphicon glyphicon-download-alt"><span>Download</span></a></div></li>
                        }
                        @if (Request.IsAuthenticated && User.IsInRole("Agonista") | User.IsInRole("Ex agonista") | User.IsInRole("Maestro"))
                        {
                            <li><div><a href="@Url.Action("Agonisti", "Home")" class="glyphicon glyphicon-text-color"><span>Agonisti</span></a></div></li>
                        }
                        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li><div><a href="@Url.Action("Index", "RolesAdmin")" class="glyphicon glyphicon-tag"><span>Ruoli</span></a></div></li>
                            <li><div><a href="@Url.Action("Index", "UsersAdmin")" class="glyphicon glyphicon-user"><span>Utenti</span></a></div></li>
                            <li><div><a href="@Url.Action("Index", "Eventis")" class="glyphicon glyphicon-list-alt"><span>Eventi</span></a></div></li>
                            <li><div><a href="@Url.Action("Index", "Documentis")" class="glyphicon glyphicon-folder-open"><span>Documenti</span></a></div></li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </header>

    @*Menu destra fisso*@
    <div class="docu">
        <ul>
            <li>
                <a href="https://www.yammer.com/testkarate/#/home" target="_blank" title="Yammer">
                    <img src="~/Content/Immagini/Yammer.png" />
                </a>

            </li>
            <li>
                <a href="https://www.instagram.com/shotokenshukai/" target="_blank" title="Instagram">
                    <img src="~/Content/Immagini/instagram.png" />
                </a>

            </li>
        </ul>
    </div>

    <div class="container body-content">
        <img class="scittaLogoVerticale" src="~/Content/Immagini/LogoVerticale.png" />
        @RenderBody()
    </div>
        <footer>
        <div class="row">
            <div class="col col-md-4">
                <h5>
                    <strong>Shotokenshukai Caravaggio ASD</strong> ®2016
                </h5>
                <p>
                    <span class="glyphicon glyphicon-earphone verde"></span>  036353187 
                </p>
                <p>
                    <span class="glyphicon glyphicon-phone verde"></span>  3356255658
                </p>
                <p>
                    <span class="glyphicon glyphicon-envelope verde"></span>  cesare@cr-consult.eu
                </p>
                <p><span class="verde">C.F.</span> 93032200169</p>

            </div>
            <div class="col col-md-4">
                <h5><strong>Social</strong></h5>
                <a href="https://www.yammer.com/testkarate/#/home"><img class="img-social" src="~/Content/Immagini/Yammer.png" /></a> <br/><br/>
                <a href="https://www.instagram.com/shotokenshukai/"><img class="img-social" src="~/Content/Immagini/instagram.png" /></a> <br />
            </div>
            <div class="col col-md-4 text-right">
                <a href="http://www.cr-consult.eu"> <span>Almish<span style="color:#FF0000" lang="it">&amp;</span>Cesàre<span style="color:#FF0000">W</span>eb</span></a>

            </div>
        </div>
        </footer>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/Scripts/lightbox-plus-jquery.min.js")
    @Scripts.Render("~/Scripts/ckeditor/ckeditor.js")
    <script src="~/Scripts/jquery.filtertable.min.js"></script>
    <script>
	$(document).ready(function() {
		$('.tablef').filterTable();
	});
    </script>

</body>
</html>